name: lite_ui
description: '一个自定义轻量级的UI库'
version: 1.0.0
homepage:

environment:
  sdk: ^3.12.2
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
